- hosts: master_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node1gokhan", es_heap_size: "30g",
    es_config: {
        cluster.name: "test-cluster",
        discovery.zen.ping.unicast.hosts: "10.120.8.107:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.memory_lock: false,
        http.cors.enabled: true,
        http.cors.allow-origin: "/.*/",
        http.cors.allow-credentials: true,
        http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length",
        http.max_content_length: 2000mb,
        indices.recovery.max_bytes_per_sec: 2000mb,
        http.content_type.required: true,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version: "5.6.2"
    ansible_user: datavis3
    es_plugins:
     - plugin: ingest-geoip



- hosts: data_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node1gokhan", es_data_dirs: "/opt/elasticsearch", es_heap_size: "30g",
    es_config: {
        discovery.zen.ping.unicast.hosts: "10.120.8.107:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.memory_lock: false,
        cluster.name: "test-cluster",
        http.cors.enabled: true,
        http.cors.allow-origin: "/.*/",
        http.cors.allow-credentials: true,
        http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length",
        http.max_content_length: 2000mb,
        indices.recovery.max_bytes_per_sec: 2000mb,
        http.content_type.required: true,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version: "5.6.2"
    ansible_user: datavis3
    es_api_port: 9200
    es_plugins:
    - plugin: ingest-geoip

- hosts: data_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node2onuralp", es_api_port: 9201, es_heap_size: "30g",
    es_config: {
        discovery.zen.ping.unicast.hosts: "10.120.8.183:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.memory_lock: false,
        cluster.name: "test-cluster",
        http.cors.enabled: true,
        http.cors.allow-origin: "/.*/",
        http.cors.allow-credentials: true,
        http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length",
        http.max_content_length: 2000mb,
        indices.recovery.max_bytes_per_sec: 2000mb,
        http.content_type.required: true,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version: "5.6.2"
    es_api_port: 9201
    ansible_user: ttrd5
    es_plugins:
    - plugin: ingest-geoip
